<div class="bulk_sku form-list" id="bulk_sku" style="display: none;">
	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Bulk add products by sku'); ?></h4>
	<textarea class="input-text" name="bulk_sku" id="bulk_sku"></textarea><br/>
	<p class="note">
		<span>
			<?php echo $this->__('Please enter a list of comma separated SKUs to select all appropriate products.'); ?>
		</span>
	</p>
</div>
