<a href="http://www.eurotext.de/" target="_blank"><span class="eurotext_logo"></span></a>

<div style="margin:10px 0"><button class="btn button" type="button" onclick="window.open('https://eurotext-ecommerce.com/translationmanager-dokumentation-support/','_blank');"><span><span><?php echo $this->__('Open Help & Support'); ?></span></span></button></div>

<div style="border:1px solid black;padding:20px;display:inline-block;">
	<strong><?php echo $this->__('Contact'); ?> Eurotext AG </strong>

	<p class="edittext" align="left">
		<span class="eurotext_logo"></span><br>
		Eurotext AG<br>
		Sch&uuml;rerstra&szlig;e 3<br>
		97080 W&uuml;rzburg<br>
		Deutschland<br><br>
        <?php echo $this->__('Phone'); ?>: +49 (0)931 35 40 50<br>
        <?php echo $this->__('Telefax'); ?>: +49 (0)931 35 40 580<br>
		E-Mail: <a href="mailto:>info@eurotext.de">info@eurotext.de</a><br>
		Web: <a href="http://www.eurotext.de" target="_blank">www.eurotext.de</a>
	</p>
</div>
