<?php
// utf8-detection: öäü€

$helper=Mage::helper('eurotext_translationmanager');

?>

<div class="content-header">
<table cellspacing="0">
    <tbody><tr>
        <td style="width:50%;"><h3 class="icon-head head-products">translationMANAGER <?php echo $this->__("Projects"); ?></h3></td>
        <td class="a-right">
            <button id="eurotext_newproject" title="New project" type="button" class="scalable add" onclick="setLocation('<?php echo $this->getNewProjectUrl(); ?>')" style=""><span><?php echo $this->__("New project"); ?></span></button>
		</td>
    </tr>
</tbody></table>
</div>

<div class="grid">
	<div class="hor-scroll">
		<table cellspacing="0" class="data" id="projectsGrid_table">
			<colgroup>
				<col width="140" class="a-center" />
				<col width="60" />
			</colgroup>
			<thead>
				<tr class="headings">
					<th><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title"><?php echo $this->__("Last update"); ?></span></a></th>
					<th><span class="nobr"><a href="#" name="entity_id" title="asc" class="sort-title"><span class="sort-title"><?php echo $this->__("ID"); ?></span></a></th>
					<th><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title"><?php echo $this->__("Project name"); ?></span></a></th>
					<th><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title"><?php echo $this->__("Source storeview"); ?></span></a></th>
					<th><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title"><?php echo $this->__("Target storeview"); ?></span></a></th>
					<th><a href="#" name="name" title="asc" class="not-sort"><span class="sort-title"><?php echo $this->__("Status"); ?></span></a></th>
					<th class="no-link last"><span class="nobr"><?php echo $this->__("Action"); ?></span></th>
				</tr>
				<!--<tr class="filter">
					<th><span class="timestamp"><input type="text" id="last_update" value="" class="input-text no-changes"></span></th>
					<th><span class="number"><input type="text" id="id" value="" class="input-text no-changes"></span></th>
					<th><span class="text"><input type="text" id="project_name" value="" class="input-text no-changes"></span></th>					
					<th><span class="text">
						<select id="storeview_src" class="input-text no-changes">
							<option value="-1">-- Choose Filter --</option>
							<option value="0">xxx</option>
							<option value="1">yyy</option>
						</select>
					</span></th>					
					<th><span class="text">
						<select id="storeview_dst" class="input-text no-changes">
							<option value="-1">-- Choose Filter --</option>
							<option value="0">xxx</option>
							<option value="1">yyy</option>
						</select>
					</span></th>	
					<th><span class="text">
						<select id="project_status" class="input-text no-changes">
							<option value="-1">Show All</option>
							<option value="1">New</option>
							<option value="2">In progress</option>
						</select>
					</span></th>	
					<th class=" no-link last">&nbsp;</th>
				</tr>-->
			</thead>
			<tbody>
				<?php
					$projects=$this->getProjects();
					if (count($projects)==0)
					{
						?>
							<tr class="even pointer">
								<td colspan="7">- <?php echo $this->__("No projects created"); ?> -</td>
							</tr>
						<?php
					}
					else
					{
						$alt=0;
						foreach($projects as $project)
						{
							$alt=1-$alt;
							$trClass="even pointer";
							if ($alt==1)
							{
								$trClass="odd pointer";
							}					
							
							if ($project['id']==$this->getSelectedProjectId())
							{
								$trClass="selected_project pointer";
							}
							
							$row_url=$this->getProjectUrl($project['id']);
							
							echo "<tr title='".$row_url."' class='".$trClass."'>";
							{
								echo "<td>".$project['last_update']."</td>";
								echo "<td>".$project['id']."</td>";
								echo "<td>".$this->htmlEscape($project['project_name'])."</td>";
								echo "<td>".$this->getStoreviewTitle($project['storeview_src'])."</td>";
								echo "<td>".$this->getStoreviewTitle($project['storeview_dst'])."</td>";
								echo "<td>".$this->getStatusText($project['project_status'])."</td>";
								echo "<td>";									
									
									if ($project['project_status']==0)	// new
									{
										echo "<a href='".$row_url."'>".$this->__("Edit")."</a>";
									}
									else if ($project['project_status']==1)	// in_progress
									{
										echo "<a href='".$row_url."'>".$this->__("Import")."</a>";
									}
									else if ($project['project_status']==2)	// in_progress
									{
										echo "<a href='".$row_url."'>".$this->__("Import")."</a>";
									}
									else if ($project['project_status']==3)	// done
									{
										echo "<a href='".$row_url."'>".$this->__("Loaded")."</a>";
									}
									
									$rowdel_url=$this->getProjectDeleteUrl($project['id']);
									echo " &nbsp; <a href='".$rowdel_url."' onclick='return eurotext_confirmdelete()'>".$this->__("Delete")."</a>";
									
									if ($project['project_status']>0)
									{
										$rowreset_url=$this->getProjectResetUrl($project['id']);
										echo " &nbsp; <a href='".$rowreset_url."' onclick='return eurotext_confirmreset()'>".$this->__("Reset")."</a>";
									}

									echo "<input type='hidden' id='dummyinput_".$project['id']."' value='1' />";	// magento's grid needs this
								echo "</td>";
							}
							echo "</tr>";
						}
					}
				?>
			</tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
    eurotextGridJsObject = new varienGrid('projectsGrid', '', 'page', 'sort', 'dir', 'product_filter');
    eurotextGridJsObject.useAjax = '1';
	eurotextGridJsObject.rowClickCallback = openGridRow;
</script>

<hr size="1" color="black" style="margin:20px;" />

<?php
	$project_id=$this->getSelectedProjectId();
	if ($project_id>0)
	{
		$project=$this->getSelectedProject();
		
		echo "<script>";
		echo "var eurotext_project_saveurl='".$this->getSaveProjectUrl()."';";
		echo "var eurotext_project_sendurl='".$this->getAjaxExportUrl()."';";
		echo "var eurotext_project_importstepurl='".$this->getAjaxImportStepUrl()."';";
		echo "var eurotext_project_id=".$project['id'].";";		
		echo "var eurotext_formkey='".Mage::getSingleton('core/session')->getFormKey()."'";
		echo "</script>";

		$uploadboxTitle=$this->__("Quote request");
		
		$disabledStr="";
		$cannotChangeInfo="";
		if ($project['project_status']>0)
		{
			$uploadboxTitle=$this->__("Import translations");

			$disabledStr=" disabled='disabled'";
			$cannotChangeInfo="<span style='font-size:10pt;color:red;font-weight:bold;'>".$this->__("Already submitted. Project settings can no longer be edited.")."</span>";
		}
		
		$canExportUrlKeysStyle="";
		if($helper->urlKeyScopeIsGlobal())
		{
			$canExportUrlKeysStyle="disabled='disabled' style='color:gray;'";
			$project['export_urlkeys']=false;
		}
?>
<div class="project_settings">
			
				<div id="seite_links" style="display:inline-block;margin-right:10px;">
				<div class="grid eurotext_grid">
				<table class="data" cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">
					<tr class="headings">
						<td colspan="4" class="eurotext_head2"><?php echo $this->__("Project settings"); ?> '<?php echo $this->htmlEscape($project['project_name']); ?>' (Nr <?php echo $project_id; ?>) <?php echo $cannotChangeInfo; ?></td>
					</tr>
					<tr class="headings">
						<td class="eurotext_head"><?php echo $this->__("Action"); ?></td>
						<td class="eurotext_head">&nbsp;</td>
						<td class="eurotext_head"><?php echo $this->__("Note"); ?></td>
						<td class="eurotext_head"><?php echo $uploadboxTitle; ?></td>
					</tr>
					<tr>
						<td class="eurotext_td"><?php echo $this->__("Project name"); ?></td>
						<td>
							<input <?php echo $disabledStr; ?> type="text" class="editinput" size="50" maxlength="255" autocomplete="off" id="form_project_name" value="<?php echo $this->htmlEscape($project['project_name']); ?>" >
						</td>
						<td><?php echo $this->__("Create a unique project name here. This will allow you better recognize your various projects later."); ?></td>
						<td rowspan="10" style="background-color:#FAFAFA;">
							<!-- Anfang rechte Seite -->
							<div class="seite_rechts" style="display:inline-block;">
								
								<?php
									if ($project['project_status']==0)
									{
								?>
								
								<div style="margin:10px;border:2px dashed black; padding:10px;display:inline-block; background-color:#F7C27E;">
									<table cellspacing="0" cellpadding="0" border="0" style="border:0px;">
										<tr style="border:0px;">
											<td style="border:0px;background-color:#F7C27E;"><?php echo $this->__("Select product texts, category texts, or CMS pages for translation."); ?><br><br>
							<?php echo $this->__("Clicking the button below will transmit the selected texts to the translation portal, and you will receive a detailed quote for the translation of your texts within 24h (weekdays)."); ?><br><br>
							<?php echo $this->__("This process may take a few minutes depending on project size. Please wait until a message is displayed that the import has been completed."); ?></td>	
										</tr>
										<tr style="border:0px;">
											<td style="border:0px;background-color:#F7C27E;">
												<input id="eurotext_angebot_btt" class="et_btt" type="button" name="save" value="&nbsp;&nbsp;&nbsp;<?php echo $this->__("Request your free quote now"); ?>&nbsp;&nbsp;&nbsp;" onClick="return eurotext_sendproject()" /><br>
											</td>
										</tr>
										<tr style="border:0px;">
											<td style="border:0px;background-color:#F7C27E;"><span id="eurotext_sendprogress"></span></td>
										</tr>
									</table>
								</div>
								
								<?php
									}
									
									if ($project['project_status']==1)
									{
								?>
								
								<div style="margin:10px;border:2px dashed black; padding:10px;display:inline-block;background-color:#F7C27E;">
									<form id="zipfile_form" action="<?php echo $this->getUploadUrl(); ?>" method="post" enctype="multipart/form-data">
									<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
									<table cellspacing="0" cellpadding="0" border="0" style="border:0px;">
										<tr>
											<td style="border:0px;background-color:#F7C27E;">
												<div><?php echo $this->__("Import the *.zip file containing the finished translations here"); ?>:</div>
												<div><input type="file" accept="application/zip" name="zipfile" id="zipfile" /></div>						
											</td>	
										</tr>
										<tr height="10">
											<td style="border:0px;background-color:#F7C27E;">&nbsp;</td>
										</tr>
										<tr>
											<td style="border:0px;background-color:#F7C27E;text-align:center;">
												<a class="et_btt" href="#" onclick="return eurotext_uploadzip()"><?php echo $this->__("Import translations now"); ?></a>
											</td>
										</tr>							
									</table>

                                        <?php
                                        if ($helper->getDebugMode())
                                        {
                                            $zip_url=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)."var/export/".$project['zip_filename'];
                                            echo '<div>&nbsp;</div>';
									        echo '<div>(Debug) Vom Modul erstellte *.zip-Datei: <a href="'.$zip_url.'">'.$project['zip_filename'].'</a></div>';
                                        }
                                        ?>

									</form>
								</div>
								
								<?php
                                    }
									
									if ($project['project_status']==2)
									{
								?>
								
								<div style="margin:10px;border:2px dashed black; padding:10px;display:inline-block;background-color:#F7C27E;">
									<table cellspacing="0" cellpadding="0" border="0" style="border:0px;">
										<tr>
											<td style="border:0px;background-color:#F7C27E;">
												<div><?php echo $this->__("The *.zip-File was extracted. Click “Begin import” to upload the translations."); ?></div>					
												<div><?php echo $this->__("We recommend creating a backup before importing."); ?></div>
											</td>	
										</tr>
										<tr height="10">
											<td style="border:0px;background-color:#F7C27E;">&nbsp;</td>
										</tr>
										<tr>
											<td style="border:0px;background-color:#F7C27E;text-align:center;">
												<a class="et_btt" id="eurotext_importbtt" href="#" onclick="return eurotext_startimport()"><?php echo $this->__("Begin import"); ?></a>
											</td>
										</tr>	
										<tr>
											<td style="border:0px;background-color:#F7C27E;"><span id="eurotext_importprogress"></span></td>
										</tr>						
									</table>
								</div>
								
								<?php
									}
								?>					
							</div>
							<!-- Ende rechte Seite -->
						</td>
					</tr>
					<tr>
						<td>Storeview</td>
						<td class="eurotext_td">
							<div><?php echo $this->__("Source storeview"); ?></div>
							<div><?php echo $this->getSpracheSelect('form_storeview_src',$project['storeview_src'],$disabledStr); ?></div>
							<div>&nbsp;</div>
							<div><?php echo $this->__("Target storeview"); ?></div>
							<div><?php echo $this->getSpracheSelect('form_storeview_dst',$project['storeview_dst'],$disabledStr); ?></div>
						</td>
						<td><?php echo $this->__("Specify the source language (source storeview) and the target language (target storeview).<br/>The language of the current storeview is shown in brackets. You can amend the language setting in Magento if the language shown is incorrect:<br/>System -> Configuration, then select “Storeview” at the top left. Set the correct language via General -> Locale Options (here you can also double-check all other language/country settings for your shop)"); ?></td>
					</tr>																
					<tr>
						<td style="text-align:center;">
							<input <?php echo $disabledStr; ?> class="et_btt" type="button" value="<?php echo $this->__("Select products"); ?>" class="eurotext_td" onclick="return eurotext_select('<?php echo $this->getSelectUrl('selectproducts',$project_id); ?>','<?php echo $project_id; ?>','form_productmode')">
						</td>
						<td><?php echo $this->__("or"); ?> <input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_productmode" value='1' <?php echo $this->GetCheckedStr($project['productmode']); ?>> <?php echo $this->__("Select all products without existing translations"); ?></td>
						<td><?php echo $this->__("Selecting this check box will assign all items for which no text has been created in the target language.<br><b>Important: All previous assignments will be cancelled!</b>"); ?></b></td>						
					</tr>
					<tr>
						<td style="text-align:center;">
							<input <?php echo $disabledStr; ?> type="button" value="<?php echo $this->__("Select categories"); ?>" class="et_btt" onclick="return eurotext_select('<?php echo $this->getSelectUrl('selectcategories',$project_id); ?>','<?php echo $project_id; ?>','form_categorymode')" >
						</td>
						<td><?php echo $this->__("or"); ?> <input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_categorymode" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['categorymode']); ?>> <?php echo $this->__("Select all categories without existing translations"); ?></td>
						<td><?php echo $this->__("Selecting this check box will assign all categories for which no texts have been created in the target language.<br/><b>Important: All previous assignments will be cancelled!</b>"); ?></td>						
					</tr>	
					<tr>
						<td style="text-align:center;">
							<input <?php echo $disabledStr; ?> type="button" value="<?php echo $this->__("Select CMS pages"); ?>" class="et_btt" onclick="return eurotext_select('<?php echo $this->getSelectUrl('selectcmspages',$project_id); ?>','<?php echo $project_id; ?>','form_cmsmode')" >
						</td>
						<td><?php echo $this->__("or"); ?> <input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_cmsmode" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['cmsmode']); ?>> <?php echo $this->__("Select all CMS pages without existing translations"); ?></td>
						<td><?php echo $this->__("Selecting this check box will assign all CMS pages without existing target language translations.<br/><b>Important: All previous assignments will be cancelled!</b>"); ?></td>
					</tr>
					<tr>
						<td style="text-align:center;">
							<input <?php echo $disabledStr; ?> type="button" value="<?php echo $this->__("Select email templates"); ?>" class="et_btt" onclick="return eurotext_select('<?php echo $this->getSelectUrl('selectemails',$project_id); ?>','<?php echo $project_id; ?>','form_templatemode')" >
						</td>
						<td><?php echo $this->__("or"); ?> <input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_templatemode" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['templatemode']); ?>> <?php echo $this->__("Select all email templates without existing translations"); ?></td>
						<td><?php echo $this->__("Selecting this check box will export all email templates without a counterpart in the target language.<br><b>Important: All previous assignments will be cancelled!</b>"); ?></td>
					</tr>
					<tr>
						<td style="text-align:center;">
							<input <?php echo $disabledStr; ?> type="button" value="<?php echo $this->__("Select language files"); ?>" class="et_btt" onclick="return eurotext_select('<?php echo $this->getSelectUrl('selectlangfiles',$project_id); ?>','<?php echo $project_id; ?>','form_langfilesmode')" >
						</td>
						<td><?php echo $this->__("or"); ?> <input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_langfilesmode" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['langfilesmode']); ?>> <?php echo $this->__("Select all entries in language files without existing translations"); ?></td>
						<td><?php echo $this->__("Selecting this check box will trigger a check of all language files for missing translations. All entries without an existing translation will be exported.<br><b>Important: All previous assignments will be cancelled!</b>"); ?></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Additional settings"); ?></td>
						<td>							
							<div><input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_export_seo" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['export_seo']); ?>> 1) <?php echo $this->__("Export SEO content?"); ?></div>
							<div>&nbsp;</div>
							<div><input <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_export_attributes" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['export_attributes']); ?>> 2) <?php echo $this->__("Export attributes und attribute options?"); ?></div>
							<div>&nbsp;</div>
							<div <?php echo $canExportUrlKeysStyle; ?>><input <?php echo $canExportUrlKeysStyle; ?> <?php echo $disabledStr; ?> class="eurotext_td" type="checkbox" id="form_export_urlkeys" autocomplete="off" value='1' <?php echo $this->GetCheckedStr($project['export_urlkeys']); ?>> 3) <?php echo $this->__("Export URL keys?"); ?></div>
						</td>
						<td>
							<div>1) <?php echo $this->__("Select this check box if you wish to translate your SEO content (keywords, meta tags, etc.)."); ?></div>
							<div>&nbsp;</div>							
							<div>2) <?php echo $this->__("Select this check box if you wish to translate product attributes and associated values."); ?></div>
							<div>&nbsp;</div>
							<div <?php echo $canExportUrlKeysStyle; ?>>3) <?php echo $this->__("Select this check box if you wish to translate product and category URLs"); ?></div>
						</td>
					</tr>			
				</table>										
				</div>
				</div>
				
				<div style="margin-top:20px;">
					<input <?php echo $disabledStr; ?> type="submit" class="et_btt" id="btt_saveproject" value="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->__("Save"); ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" onclick="return eurotext_saveproject(eurotext_reloadpage)">
					<br><span id="eurotext_saving"></span>
				</div>
				
				<!-- Ende linke Seite -->
			</td>
			<td>		
				
			</td>
		</tr>
	</table>
</div>
<?php
	}
?>

<div>&nbsp;</div>
<div class="actions">
<ul><li><a class="firstitem" id="btn.help" href="<?php echo Mage::helper('adminhtml')->getUrl('*/eurotext_translationmanager_help/index'); ?>" target="_blank"><?php echo $this->__("Open help"); ?></a></li></ul>
</div>