<?php
// utf8-detection: öäü€

?>

<form id="et_form" action="<?php echo $this->getPostBackUrl(); ?>" method="get">
<div class="eurotext_confighead"><?php echo $this->__("Please enter your contact information here"); ?></div>
<div class="eurotext_config">
                <table width="98%" class="form">
                    <tr>
                        <td colspan="2" class="eurotext_edittext"><?php echo $this->__("This information is your personal access data for the Eurotext AG translation portal.<br/>Registration is free of charge. You will receive your personal access information within 24 hours (weekdays)."); ?></td>
                    </tr>
				</table>
				<table class="form">
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Shop Name"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_shopname" type="text" name="register_shopname" size="95"
                            class="defaultcontent" 
                            value="<?php echo $this->getSetting("register_shopname"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Shop URL"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_shopurl" type="text" name="register_url" size="95"
                            class="defaultcontent" 
                            value="<?php echo $this->getSetting("register_url"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("eMail Address"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_email" type="text" name="register_email" size="95"
                              class="defaultcontent" 
                              value="<?php echo $this->getSetting("register_email"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Salutation"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext">
                            <select disabled="disabled" name="register_sal" id="register_sal" >
                                <option value="MR" <?php if ($this->getSetting("register_sal")=="MR") { echo " selected='selected'"; } ?>><?php echo $this->__("Mr."); ?></option>
                                <option value="MRS" <?php if ($this->getSetting("register_sal")=="MRS") { echo " selected='selected'"; } ?>><?php echo $this->__("Ms."); ?></option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("First Name"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_firstname" type="text" name="register_fname" size="95"
                            class="defaultcontent" 
                            value="<?php echo $this->getSetting("register_fname"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Last Name"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_lastname" type="text" name="register_lname" size="95"
                            class="defaultcontent" 
                            value="<?php echo $this->getSetting("register_lname"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Company"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_company" type="text" name="register_company" size="95"
                            class="defaultcontent" 
                            value="<?php echo $this->getSetting("register_company"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Street"); ?> / <?php echo $this->__("House No"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_street" type="text" name="register_street" size="83"
                              class="defaultcontent"  value="<?php echo $this->getSetting("register_street"); ?>" >
                            <input disabled="disabled" id="et_register_hnumber" type="text" name="register_hnumber" size="8"
                              class="defaultcontent"  value="<?php echo $this->getSetting("register_hnumber"); ?>" >
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Zip"); ?> / <?php echo $this->__("City"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_zip" type="text" name="register_zip" size="8"
                              class="defaultcontent"  value="<?php echo $this->getSetting("register_zip"); ?>" >
                            <input disabled="disabled" id="et_register_city" type="text" name="register_city" size="83"
                                 class="defaultcontent"  value="<?php echo $this->getSetting("register_city"); ?>">
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Country"); ?>&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext">
                            <select disabled="disabled" name="register_country" id="register_country" >
                                                            <option value="Deutschland">Deutschland</option>
                                                            <option value="&Ouml;sterreich">&Ouml;sterreich</option>
                                                            <option value="Schweiz">Schweiz</option>
                                                            <option value="Afghanistan">Afghanistan</option>
                                                            <option value="&Auml;gypten">&Auml;gypten</option>
                                                            <option value="Albanien">Albanien</option>
                                                            <option value="Algerien">Algerien</option>
                                                            <option value="Andorra">Andorra</option>
                                                            <option value="Angola">Angola</option>
                                                            <option value="Antigua und Barbuda">Antigua und Barbuda</option>
                                                            <option value="&Auml;quatorialguinea">&Auml;quatorialguinea</option>
                                                            <option value="Argentinien">Argentinien</option>
                                                            <option value="Armenien">Armenien</option>
                                                            <option value="Aserbaidschan">Aserbaidschan</option>
                                                            <option value="&Auml;thiopien">&Auml;thiopien</option>
                                                            <option value="Australien">Australien</option>
                                                            <option value="Bahamas">Bahamas</option>
                                                            <option value="Bahrain">Bahrain</option>
                                                            <option value="Bangladesch">Bangladesch</option>
                                                            <option value="Barbados">Barbados</option>
                                                            <option value="Wei&szlig;russland">Wei&szlig;russland</option>
                                                            <option value="Belgien">Belgien</option>
                                                            <option value="Belize">Belize</option>
                                                            <option value="Benin">Benin</option>
                                                            <option value="Bhutan">Bhutan</option>
                                                            <option value="Bolivien">Bolivien</option>
                                                            <option value="Bosnien-Herzegowina">Bosnien-Herzegowina</option>
                                                            <option value="Botsuana">Botsuana</option>
                                                            <option value="Brasilien">Brasilien</option>
                                                            <option value="Brunei Darussalam">Brunei Darussalam</option>
                                                            <option value="Bulgarien">Bulgarien</option>
                                                            <option value="Burkina Faso">Burkina Faso</option>
                                                            <option value="Burundi">Burundi</option>
                                                            <option value="Cayman Islands">Cayman Islands</option>
                                                            <option value="Chile">Chile</option>
                                                            <option value="China">China</option>
                                                            <option value="Cookinseln">Cookinseln</option>
                                                            <option value="Costa Rica">Costa Rica</option>
                                                            <option value="Elfenbeink&uuml;ste">Elfenbeink&uuml;ste</option>
                                                            <option value="D&auml;nemark">D&auml;nemark</option>
                                                            <option value="Dominica">Dominica</option>
                                                            <option value="Dominikanische Republik">Dominikanische Republik</option>
                                                            <option value="Dschamahirija">Dschamahirija</option>
                                                            <option value="Dschibuti">Dschibuti</option>
                                                            <option value="Ecuador">Ecuador</option>
                                                            <option value="El Salvador">El Salvador</option>
                                                            <option value="England">England</option>
                                                            <option value="Eritrea">Eritrea</option>
                                                            <option value="Estland">Estland</option>
                                                            <option value="Fidschi">Fidschi</option>
                                                            <option value="Finnland">Finnland</option>
                                                            <option value="Frankreich">Frankreich</option>
                                                            <option value="Gabon">Gabon</option>
                                                            <option value="Gambia">Gambia</option>
                                                            <option value="Georgien">Georgien</option>
                                                            <option value="Ghana">Ghana</option>
                                                            <option value="Grenada">Grenada</option>
                                                            <option value="Griechenland">Griechenland</option>
                                                            <option value="Guatemala">Guatemala</option>
                                                            <option value="Guinea">Guinea</option>
                                                            <option value="Guinea-Bissau">Guinea-Bissau</option>
                                                            <option value="Guyana">Guyana</option>
                                                            <option value="Haiti">Haiti</option>
                                                            <option value="Heiliger Stuhl">Heiliger Stuhl</option>
                                                            <option value="Honduras">Honduras</option>
                                                            <option value="Indien">Indien</option>
                                                            <option value="Indonesien">Indonesien</option>
                                                            <option value="Irak">Irak</option>
                                                            <option value="Iran">Iran</option>
                                                            <option value="Irland">Irland</option>
                                                            <option value="Island">Island</option>
                                                            <option value="Israel">Israel</option>
                                                            <option value="Italien">Italien</option>
                                                            <option value="Jamaika">Jamaika</option>
                                                            <option value="Japan">Japan</option>
                                                            <option value="Jemen">Jemen</option>
                                                            <option value="Jordanien">Jordanien</option>
                                                            <option value="Jugoslawien">Jugoslawien</option>
                                                            <option value="Kambodscha">Kambodscha</option>
                                                            <option value="Kamerun">Kamerun</option>
                                                            <option value="Kanada">Kanada</option>
                                                            <option value="Kap Verde">Kap Verde</option>
                                                            <option value="Kasachstan">Kasachstan</option>
                                                            <option value="Katar">Katar</option>
                                                            <option value="Kenia">Kenia</option>
                                                            <option value="Kirgisistan">Kirgisistan</option>
                                                            <option value="Kiribati">Kiribati</option>
                                                            <option value="Kolumbien">Kolumbien</option>
                                                            <option value="Komoren">Komoren</option>
                                                            <option value="Kongo">Kongo</option>
                                                            <option value="Kongo, Dem. Republik">Kongo, Dem. Republik</option>
                                                            <option value="Korea, Dem. Volksrep.">Korea, Dem. Volksrep.</option>
                                                            <option value="Korea, Republik">Korea, Republik</option>
                                                            <option value="Kosovo">Kosovo</option>
                                                            <option value="Kroatien">Kroatien</option>
                                                            <option value="Kuba">Kuba</option>
                                                            <option value="Kuwait">Kuwait</option>
                                                            <option value="Laos">Laos</option>
                                                            <option value="Lesotho">Lesotho</option>
                                                            <option value="Lettland">Lettland</option>
                                                            <option value="Libanon">Libanon</option>
                                                            <option value="Liberia">Liberia</option>
                                                            <option value="Libysch-Arabische">Libysch-Arabische</option>
                                                            <option value="Liechtenstein">Liechtenstein</option>
                                                            <option value="Litauen">Litauen</option>
                                                            <option value="Luxemburg">Luxemburg</option>
                                                            <option value="Madagaskar">Madagaskar</option>
                                                            <option value="Malawi">Malawi</option>
                                                            <option value="Malaysia">Malaysia</option>
                                                            <option value="Malediven">Malediven</option>
                                                            <option value="Mali">Mali</option>
                                                            <option value="Malta">Malta</option>
                                                            <option value="Marokko">Marokko</option>
                                                            <option value="Marshallinseln">Marshallinseln</option>
                                                            <option value="Mauretanien">Mauretanien</option>
                                                            <option value="Mauritius">Mauritius</option>
                                                            <option value="Mazedonien">Mazedonien</option>
                                                            <option value="Mexiko">Mexiko</option>
                                                            <option value="Mikronesien">Mikronesien</option>
                                                            <option value="Moldau">Moldau</option>
                                                            <option value="Monaco">Monaco</option>
                                                            <option value="Mongolei">Mongolei</option>
                                                            <option value="Mosambik">Mosambik</option>
                                                            <option value="Myanmar">Myanmar</option>
                                                            <option value="Namibia">Namibia</option>
                                                            <option value="Nauru">Nauru</option>
                                                            <option value="Nepal">Nepal</option>
                                                            <option value="Neuseeland">Neuseeland</option>
                                                            <option value="Nicaragua">Nicaragua</option>
                                                            <option value="Niederlande">Niederlande</option>
                                                            <option value="Niger">Niger</option>
                                                            <option value="Nigeria">Nigeria</option>
                                                            <option value="Niue">Niue</option>
                                                            <option value="Norwegen">Norwegen</option>
                                                            <option value="Oman">Oman</option>
                                                            <option value="Osttimor">Osttimor</option>
                                                            <option value="Pakistan">Pakistan</option>
                                                            <option value="Palau">Palau</option>
                                                            <option value="Palestina">Palestina</option>
                                                            <option value="Panama">Panama</option>
                                                            <option value="Papua-Neuguinea">Papua-Neuguinea</option>
                                                            <option value="Paraguay">Paraguay</option>
                                                            <option value="Peru">Peru</option>
                                                            <option value="Philippinen">Philippinen</option>
                                                            <option value="Polen">Polen</option>
                                                            <option value="Portugal">Portugal</option>
                                                            <option value="Ruanda">Ruanda</option>
                                                            <option value="Rum&auml;nien">Rum&auml;nien</option>
                                                            <option value="Russische F&ouml;deration">Russische F&ouml;deration</option>
                                                            <option value="Salomonen">Salomonen</option>
                                                            <option value="Sambia">Sambia</option>
                                                            <option value="Samoa">Samoa</option>
                                                            <option value="San Marino">San Marino</option>
                                                            <option value="São Tomé und Príncipe">São Tomé und Príncipe</option>
                                                            <option value="Saudi-Arabien">Saudi-Arabien</option>
                                                            <option value="Schweden">Schweden</option>
                                                            <option value="Senegal">Senegal</option>
                                                            <option value="Serbien">Serbien</option>
                                                            <option value="Seychellen">Seychellen</option>
                                                            <option value="Sierra Leone">Sierra Leone</option>
                                                            <option value="Simbabwe">Simbabwe</option>
                                                            <option value="Singapur">Singapur</option>
                                                            <option value="Slowakei">Slowakei</option>
                                                            <option value="Slowenien">Slowenien</option>
                                                            <option value="Somalia">Somalia</option>
                                                            <option value="Spanien">Spanien</option>
                                                            <option value="Sri Lanka">Sri Lanka</option>
                                                            <option value="St. Kitts und Nevis">St. Kitts und Nevis</option>
                                                            <option value="St. Lucia">St. Lucia</option>
                                                            <option value="St. Vincent / Grenadinen">St. Vincent / Grenadinen</option>
                                                            <option value="S&uuml;dafrika">S&uuml;dafrika</option>
                                                            <option value="Sudan">Sudan</option>
                                                            <option value="Suriname">Suriname</option>
                                                            <option value="Swasiland">Swasiland</option>
                                                            <option value="Syrien">Syrien</option>
                                                            <option value="Tadschikistan">Tadschikistan</option>
                                                            <option value="Taiwan">Taiwan</option>
                                                            <option value="Tansania">Tansania</option>
                                                            <option value="Thailand">Thailand</option>
                                                            <option value="Togo">Togo</option>
                                                            <option value="Tonga">Tonga</option>
                                                            <option value="Trinidad und Tobago">Trinidad und Tobago</option>
                                                            <option value="Tschad">Tschad</option>
                                                            <option value="Tschechische Republik">Tschechische Republik</option>
                                                            <option value="Tunesien">Tunesien</option>
                                                            <option value="T&uuml;rkei">T&uuml;rkei</option>
                                                            <option value="Turkmenistan">Turkmenistan</option>
                                                            <option value="Tuvalu">Tuvalu</option>
                                                            <option value="Uganda">Uganda</option>
                                                            <option value="Ukraine">Ukraine</option>
                                                            <option value="Ungarn">Ungarn</option>
                                                            <option value="Uruguay">Uruguay</option>
                                                            <option value="USA">USA</option>
                                                            <option value="Usbekistan">Usbekistan</option>
                                                            <option value="Vanuatu">Vanuatu</option>
                                                            <option value="Vatikanstadt">Vatikanstadt</option>
                                                            <option value="Venezuela">Venezuela</option>
                                                            <option value="Vereinigte Arabische Emirate">Vereinigte Arabische Emirate</option>
                                                            <option value="Vereinigtes K&ouml;nigreich">Vereinigtes K&ouml;nigreich</option>
                                                            <option value="Vietnam">Vietnam</option>
                                                            <option value="Zentralafrikanische Republik">Zentralafrikanische Republik</option>
                                                            <option value="Zypern">Zypern</option>
                                                        </select>
														
														<script>
														jQuery(document).ready(function()
														{
															var selCountry="<?php echo $this->getSetting("register_country"); ?>";
															jQuery("#register_country").val(selCountry);
														});
														</script>
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext"><label><?php echo $this->__("Phone"); ?>:&nbsp;&nbsp;</label></td>
                        <td class="eurotext_edittext"><input disabled="disabled" id="et_register_tel" type="text" name="register_telefon" size=95
                             class="defaultcontent" 
                             value="<?php echo $this->getSetting("register_telefon"); ?>">
                        </td>
                    </tr>
                    <tr>
                        <td class="eurotext_edittext" colspan="2" style="padding-left:8px;"><br><?php echo $this->__("Please enter all requested information!"); ?><br><br><b><?php echo $this->__("Important"); ?>:</b><br><?php echo $this->__("Any information you provide is voluntary. Your data will be used for the purpose of logging in to the translation portal and for project processing in your dealings with Eurotext AG only. Your information will not be forwarded to third parties. You can request a deletion of your information at any time by sending an email to <a href='mailto:datenschutz@eurotext.de'>privacy@eurotext.de</a>."); ?></td>
                    </tr>					
                </table>
			</div>
		</div>
		
		<div style="margin-top:20px;">
			<table cellpadding="0" cellspacing="0" style="width:100%;">
				<tr>
					<td class="eurotext_edittext">
						<span class="btn">
							<input class="et_btt" disabled="disabled" type="submit" class="btn" id="register_submit" value="&nbsp;&nbsp;&nbsp;<?php echo $this->__("Save and send"); ?>&nbsp;&nbsp;&nbsp;">
						</span>
						<span class="btn" style="margin-left:230px;">
							<input class="et_btt" style="display:none;" id="register_change" type="submit" onclick="return eurotext_unlock2()" value="&nbsp;&nbsp;&nbsp;<?php echo $this->__("Edit information"); ?>&nbsp;&nbsp;&nbsp;">
						</span>
					</td>
					<td style="text-align:right;"><?php echo $this->__("Module-Version"); ?>: <?php echo $this->getModuleVersion(); ?></td>
				</tr>
				<tr>
					<td colspan="2" class="eurotext_edittext" id="et_statusmsg"><?php echo $this->getMessage(); ?></td>
				</tr>
			</table>
		</div>
	
	  <?php
		if ($this->isSaved()==false)
		{
			// eMail was never send, unlock fields:
			echo "<script>eurotext_unlock();</script>";
		}
		else
		{
			// Enable 'Edit information' button
			echo "<script>jQuery('#register_change').show();</script>";
		}
	  ?>
</form>