<?php
// allow utf8-detection: öäü€

global $visibleCatIds;
$visibleCatIds=array();

?>

<div class="eurotext_layertitle"><?php echo $this->__("Select categories"); ?></div>
<div class="eurotext_layerstrip"></div>

<table cellpadding="0" cellspacing="0" style="width:100%;border:1px solid #E6E6E6;">
	<tr>
		<td class="eurotext_layercellheader"><?php echo $this->__("Select categories"); ?></td>
		<td class="eurotext_layercellheader" style="border-left:1px solid #E6E6E6;"><?php echo $this->__("Selected categories"); ?></td>
	</tr>
	<tr>
		<td style="width:50%;vertical-align:top;">
			<div style="margin:20px;">
			<?php 			
				
				function drawCategory($category, $openedPathIds, $selectedCategoryIds, $level)
				{	
					global $visibleCatIds;
					
					$category_id=$category->getId();
					
					$checkStr="";
					if (in_array($category_id,$selectedCategoryIds))
					{
						$checkStr="checked='checked'";
					}
					
					array_push($visibleCatIds,$category_id);
				
					echo "<table cellpadding=0 cellspacing=0>";			
					echo "<tr>";
					echo "  <td class='et_tc'>&nbsp;</td>";
					echo "  <td class='et_tc'><input ".$checkStr." type='checkbox' id='et_selcategory1_".$category_id."' class='et_selcategoryitem et_selcategory_".$category_id."' onchange=\"eurotext_selectcategory('1','".$category_id."')\" /></td>";
					echo "  <td class='et_tc'>";
					echo "     <div>".$category->getName()."</div>";
					
					{
						echo "     <div>";
						$childs=$category->getChildrenCategories();
						if ($childs!=null)
						{
							foreach($childs as $child)
							{
								drawCategory($child, $openedPathIds, $selectedCategoryIds, ($level+1));
							}			
						}		
						echo "     </div>";
					}
					
					echo "  </td>";
					echo "</tr>";
					echo "</table>";				
					
				}

				$root=$this->getRootCategory();
				$openedPathIds=$this->getOpenedPathIds();
				$selectedCategoryIds=$this->getSelectedCategoryIds();

				drawCategory($root,$openedPathIds,$selectedCategoryIds,0);
			?>
			</div>			
			
			<?php
				echo "<div style='margin:20px;'>";
				//echo "<div><a href='#' class='eurotext_selectcategories_allvisible'>".$this->__("Select all categories displayed")."</a></div>";
				echo "<div><a href='#' class='eurotext_selectcategories_all'>".$this->__("Select all categories")."</a></div>";
				echo "<div><a href='#' class='eurotext_selectcategories_none'>".$this->__("No selection")."</a></div>";
				echo "</div>";
			?>
			
		</td>
		<td style="vertical-align:top;background-color:#F2F2F2;">
			<div style="margin:20px;">
				<div id="et_saveinfo"><?php $this->__("Loading - please wait..."); ?></div>
				<div id="selectedcategories_result"></div>
			</div>
		</td>
	</tr>
</table>
<div style="text-align:center;margin-top:10px;"><a href="#" onclick="return eurotext_closeme()" class="et_btt"><?php echo $this->__("Save"); ?></a></div>
<div>&nbsp;</div>

<script>
var eurotext_selectcategories_url="<?php echo $this->getSelectCategoriesUrl(); ?>";
var eurotext_selectcategories_saveurl="<?php echo $this->getSelectCategoriesSaveUrl(); ?>";
var eurotext_formkey="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>";
var eurotext_projectid="<?php echo $this->getRequest()->getParam("id"); ?>";

jQuery(document).ready(function()
{
	eurotext_selectedcategories_send(new Array(),true,null);
	
	jQuery(".eurotext_selectcategories_all").click(function()
	{		
		var postdata=new Array();
		
		<?php
			echo "postdata['cnt']=".count($visibleCatIds).";";
			for($i=0; $i<count($visibleCatIds); $i++)
			{
				echo "postdata['category_id_".$i."']=".$visibleCatIds[$i].";";
				echo "postdata['set_".$i."']='enabled';";
			}
		?>
		
		jQuery(".et_selcategoryitem").attr("checked","checked");
				
		eurotext_selectedcategories_send(postdata,true,null);
	});
	
	jQuery(".eurotext_selectcategories_none").click(function()
	{		
		var postdata=new Array();
		postdata['cnt']=0;
		postdata['select']='none';
		
		jQuery(".et_selcategoryitem").attr("checked",false);
				
		eurotext_selectedcategories_send(postdata,true,null);
	});

});
</script>