<?php
// allow utf8-detection: öäü€

$visibleLangfiles=array();
?>

<div class="eurotext_layertitle"><?php echo $this->__("Select language files"); ?></div>
<div class="eurotext_layerstrip"></div>

<table cellpadding="0" cellspacing="0" style="width:100%;border:1px solid #E6E6E6;">
	<tr>
		<td class="eurotext_layercellheader"><?php echo $this->__("Select language files"); ?></td>
		<td class="eurotext_layercellheader" style="border-left:1px solid #E6E6E6;"><?php echo $this->__("Selected language files"); ?></td>
	</tr>
	<tr>
		<td style="width:50%;vertical-align:top;">
			<div style="margin:20px;">					
			<?php
				$langfiles=$this->getLangfiles();
				
				// Results:
				echo "<table cellpadding=0 cellspacing=0>";
				echo "<tr>";
				echo "  <td class='et_th'>".$this->__("Translate")."</td>";
				echo "  <td class='et_th'>".$this->__("Filename")."</td>";
				echo "  <td class='et_th'>&nbsp;</td>";
				echo "</tr>";
										
				foreach($langfiles as $langfile)
				{
					$checkStr="";
					if ($langfile['checked'])
					{
						$checkStr="checked='checked'";
					}
					
					array_push($visibleLangfiles,$langfile['line_hash']);
					
					echo "<tr>";
					echo "  <td class='et_tc'><input ".$checkStr." type='checkbox' id='et_sellangfile1_".$langfile['line_hash']."' class='et_sellangfile et_sellangfile_".$langfile['line_hash']."' onchange=\"eurotext_selectlangfile('1','".$langfile['line_hash']."')\" /></td>";
					echo "  <td class='et_tc'>".$langfile['filename']."</td>";
					echo "  <td class='et_tc'>&nbsp;</td>";
					echo "</tr>";
				}		
				echo "</table>";
				
			?>
			</div>		
			<?php		
				echo "<div style='margin:20px;'>";
				echo "<div><a href='#' class='eurotext_selectlangfiles_allvisible'>".$this->__("Select all language files displayed")."</a></div>";
				echo "<div><a href='#' class='eurotext_selectlangfiles_all'>".$this->__("Select all language files")."</a></div>";
				echo "<div><a href='#' class='eurotext_selectlangfiles_none'>".$this->__("No selection")."</a></div>";
				echo "</div>";
			?>				
		</td>
		<td style="vertical-align:top;background-color:#F2F2F2;">
			<div style="margin:20px;">
				<div id="et_saveinfo"><?php $this->__("Loading - please wait..."); ?></div>
				<div id="selectedlangfiles_result"></div>
			</div>
		</td>
	</tr>
</table>
<div style="text-align:center;margin-top:10px;"><a href="#" onclick="return eurotext_closeme()" class="et_btt"><?php echo $this->__("Save"); ?></a></div>
<div>&nbsp;</div>

<script>
var eurotext_selectlangfiles_url="<?php echo $this->getSelectLangfilesUrl(); ?>";
var eurotext_selectlangfiles_saveurl="<?php echo $this->getSelectLangfilesSaveUrl(); ?>";
var eurotext_formkey="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>";
var eurotext_projectid="<?php echo $this->getRequest()->getParam("id"); ?>";

jQuery(document).ready(function()
{
	eurotext_selectedlangfiles_send(new Array(),null);
	
	jQuery(".eurotext_selectlangfiles_allvisible").click(function()
	{		
		var postdata=new Array();
		
		<?php
			echo "postdata['cnt']=".count($visibleLangfiles).";";
			for($i=0; $i<count($visibleLangfiles); $i++)
			{
				echo "postdata['langfile_linehash_".$i."']='".$visibleLangfiles[$i]."';\r\n";
				echo "postdata['set_".$i."']='enabled';\r\n";
			}
		?>
		
		jQuery(".et_sellangfile").attr("checked","checked");
				
		eurotext_selectedlangfiles_send(postdata,null);
		
		return false;
	});
	
	jQuery(".eurotext_selectlangfiles_all").click(function()
	{		
		var postdata=new Array();
		
		<?php
			echo "postdata['cnt']=".count($visibleLangfiles).";";
			for($i=0; $i<count($visibleLangfiles); $i++)
			{
				echo "postdata['langfile_linehash_".$i."']='".$visibleLangfiles[$i]."';\r\n";
				echo "postdata['set_".$i."']='enabled';\r\n";
			}
		?>
		
		jQuery(".et_sellangfile").attr("checked","checked");
				
		eurotext_selectedlangfiles_send(postdata,null);
		
		return false;
	});
	
	jQuery(".eurotext_selectlangfiles_none").click(function()
	{		
		var postdata=new Array();
		postdata['cnt']=0;
		postdata['select']='none';
		
		jQuery(".et_selproductitem").attr("checked",false);
				
		eurotext_selectedlangfiles_send(postdata,null);
	});
});
</script>