<?php
// allow utf8-detection: öäü€

function selected_str($curval,$checkval)
{
	if ($curval==$checkval)
	{
		return "selected='selected'";
	}

	return "";
}

$visibleProductIds=array();
$page_size=20;
$current_page=1;

$this->updateFilterData();

$val_filter_status=$this->getFilterStatus();
$val_filter_stock=$this->getFilterStock();
$val_filter_product_type=$this->getFilterProductType();

?>

<div class="eurotext_layertitle"><?php echo $this->__("Select products"); ?></div>
<div class="eurotext_layerstrip"></div>

<table cellpadding="0" cellspacing="0" style="width:100%;border:1px solid #E6E6E6;">
	<tr>
		<td class="eurotext_layercellheader"><?php echo $this->__("Filter"); ?></td>
		<td class="eurotext_layercellheader" style="border-left:1px solid #E6E6E6;"><?php echo $this->__("Select products"); ?></td>
		<td class="eurotext_layercellheader" style="border-left:2px solid #E6E6E6;"><?php echo $this->__("Selected products"); ?></td>
	</tr>
	<tr>
		<td style="vertical-align:top;min-width:250px;">

			<div style="margin:10px;">
				<table>
					<tr>
						<td><?php echo $this->__("Status"); ?>: &nbsp;</td>
						<td><select autocomplete="off" id="filter_status">
							<option value="1" <?php if ($val_filter_status==1) { echo "selected='selected'"; } ?>><?php echo $this->__("Enabled"); ?></option>
							<option value="2" <?php if ($val_filter_status==2) { echo "selected='selected'"; } ?>><?php echo $this->__("Disabled"); ?></option>
						</select></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Stock Availability"); ?>: &nbsp;</td>
						<td><select autocomplete="off" id="filter_stock">
							<option value="1" <?php if ($val_filter_stock==1) { echo "selected='selected'"; } ?>><?php echo $this->__("In Stock");  ?></option>
							<option value="0" <?php if ($val_filter_stock==0) { echo "selected='selected'"; } ?>><?php echo $this->__("Out of Stock"); ?></option>
						</select></td>
					</tr>
					<tr>
						<td><?php echo $this->__("Product Type"); ?>: &nbsp;</td>
						<td><select autocomplete="off" id="filter_product_type">
							<option value="" <?php if ($val_filter_product_type=='') { echo "selected='selected'"; } ?>><?php echo $this->__("Show all");  ?></option>
							<option value="simple" <?php if ($val_filter_product_type=='simple') { echo "selected='selected'"; } ?>><?php echo $this->__("Simple Product"); ?></option>
							<option value="grouped" <?php if ($val_filter_product_type=='grouped') { echo "selected='selected'"; } ?>><?php echo $this->__("Grouped Product"); ?></option>
							<option value="configurable" <?php if ($val_filter_product_type=='configurable') { echo "selected='selected'"; } ?>><?php echo $this->__("Configurable Product"); ?></option>
							<option value="virtual" <?php if ($val_filter_product_type=='virtual') { echo "selected='selected'"; } ?>><?php echo $this->__("Virtual Product"); ?></option>
							<option value="bundle" <?php if ($val_filter_product_type=='bundle') { echo "selected='selected'"; } ?>><?php echo $this->__("Bundle Product"); ?></option>
							<option value="downloadable" <?php if ($val_filter_product_type=='downloadable') { echo "selected='selected'"; } ?>><?php echo $this->__("Downloadable Product"); ?></option>
						</select></td>
					</tr>
				</table>
			</div>


			<table style="border-spacing:0px;margin-top:15px;width:100%;">
				<tr>
					<td class="eurotext_layercellheader"><?php echo $this->__("Category filter"); ?></td>
				</tr>
			</table>
			<div style="margin:10px;">
				<?php echo $this->getCategoryTreeHTML(); ?>
			</div>
		</td>
		<td style="vertical-align:top;">

			<div style="margin:15px;">

				<?php
					$result=$this->getSearchResult();
				?>

				<div style="margin:10px;padding:10px;">
					<table cellpadding="0" cellspacing="0">
						<tr>
							<td><input type="text" id="find_products" style="min-width:250px;" value="<?php echo htmlentities($result['find'],ENT_COMPAT,'UTF-8'); ?>" placeholder="<?php echo $this->__("Enter designation or SKU"); ?>" /></td>
							<td>&nbsp; <a href="#" onclick="return eurotext_findproducts()"><span class="eurotext_findbtt"></span></a></td>
						</tr>
					</table>
				</div>

				<!-- Search result -->
				<?php
					if ($result['result_count']>0)
					{
						$pager="";

						$current_page=$result['page_current'];
						$page_size=$result['page_size'];

						$prev_page=($current_page-1);
						$pager_prevpage="";
						if ($prev_page<1)
						{
							$pager_prevpage="<span class='eurotext_back_disabled'></span>";
						}
						else
						{
							$page_url=$this->getSelectProductsUrl()."page/".$prev_page."/find/".urlencode($result['find'])."/pagesize/".$page_size."/catids/".implode(",",$this->getOpenCatIds());
							$pager_prevpage="<a href='".$page_url."'><span class='eurotext_back_enabled'></span></a>";
						}

						$next_page=($current_page+1);
						$pager_nextpage="";
						if ($next_page>$result['page_last'])
						{
							$pager_nextpage="<span class='eurotext_next_disabled'></span>";
						}
						else
						{
							$page_url=$this->getSelectProductsUrl()."page/".$next_page."/find/".urlencode($result['find'])."/pagesize/".$page_size."/catids/".implode(",",$this->getOpenCatIds());
							$pager_nextpage="<a href='".$page_url."'><span class='eurotext_next_enabled'></span></a>";
						}

						$maxSeiten="";
						if ($result['page_last']==1)
						{
							$maxSeiten="von 1 Seite";
						}
						else
						{
							$maxSeiten="von ".$result['page_last']." Seiten";
						}

						$pager="<table cellpadding=0 cellspacing=0 style='margin:15px;'>";
						$pager.=" <tr>";
						$pager.="  	<td class='eurotext_vcenter'>".$this->__("Page")." &nbsp;</td>";
						$pager.="  	<td>&nbsp;</td>";
						$pager.="  	<td class='eurotext_vcenter'>$pager_prevpage </td>";
						$pager.="  	<td>&nbsp;</td>";
						$pager.="   <td class='eurotext_vcenter'><input style='text-align:center;width:35px;' type='text' class='eurotext_page' value='$current_page' autocomplete='off' /> </td>";
						$pager.="  	<td>&nbsp;</td>";
						$pager.="	<td class='eurotext_vcenter'>$pager_nextpage </td>";
						$pager.="  	<td>&nbsp;</td>";
						$pager.="	<td class='eurotext_vcenter'>&nbsp; $maxSeiten</td>";
						$pager.="  	<td style='width:30px;'>&nbsp;</td>";
						$pager.="	<td class='eurotext_vcenter'>";
						$pager.="		<select class='eurotext_pagesize'>";
						$pager.="			<option value='20' ".selected_str($page_size,20).">20</option>";
						$pager.="			<option value='30' ".selected_str($page_size,30).">30</option>";
						$pager.="			<option value='50' ".selected_str($page_size,50).">50</option>";
						$pager.="			<option value='100' ".selected_str($page_size,100).">100</option>";
						$pager.="			<option value='200' ".selected_str($page_size,200).">200</option>";
						$pager.="		</select>";
						$pager.="	</td>";
						$pager.="  	<td>&nbsp;</td>";
						$pager.="	<td class='eurotext_vcenter'>".$this->__('Per Page')."</td>";
						$pager.=" </tr>";
						$pager.="</table>";

						echo $pager;

						// Results:
						echo "<table cellpadding=0 cellspacing=0>";
						echo "<tr>";
						echo "  <td class='et_th'>".$this->__("Translate")."</td>";
						echo "  <td class='et_th'>".$this->__("SKU")."</td>";
						echo "  <td class='et_th'>".$this->__("Designation")."</td>";
						echo "  <td class='et_th'>&nbsp;</td>";
						echo "</tr>";

						$products=$result['products'];

						$alt=0;
						foreach($products as $product)
						{
							$checkStr="";
							if ($product['checked'])
							{
								$checkStr="checked='checked'";
							}

							$alt=1-$alt;

							// Remember visible products:
							array_push($visibleProductIds,$product['entity_id']);

							echo "<tr>";
							echo "  <td class='et_tc eurotext_r".$alt."'><input autocomplete='off' ".$checkStr." type='checkbox' id='et_selproduct1_".$product['entity_id']."' class='et_selproductitem et_selproduct_".$product['entity_id']."' onchange=\"eurotext_selectproduct('1','".$product['entity_id']."')\" /></td>";
							echo "  <td class='et_tc eurotext_r".$alt."'>".$product['sku']."</td>"; // (ID: ".$product['entity_id'].")
							echo "  <td class='et_tc eurotext_r".$alt."'>".$product['article_name']."</td>";
							echo "  <td class='et_tc eurotext_r".$alt."'>&nbsp;</td>";
							echo "</tr>";
						}

						echo "</table>";

						echo $pager;

						echo "<div>";
						echo "<div><a href='#' class='eurotext_selectproducts_allvisible'>".$this->__("Select all products displayed")."</a></div>";
						echo "<div><a href='#' class='eurotext_selectproducts_all'>".$this->__("Select all products in this category")."</a></div>";
						echo "<div><a href='#' class='eurotext_selectproducts_none'>".$this->__("No selection")."</a></div>";
						echo "</div>";
					}
					else
					{
						echo $this->__("No result");
					}

				?>
			</div>

		</td>
		<td style="vertical-align:top;background-color:#F2F2F2;">
			<div style="margin:20px;">
				<div id="et_saveinfo"><?php $this->__("Loading - Please wait")."..."; ?></div>
				<div id="selectedproducts_result"></div>
			</div>
		</td>
	</tr>
</table>
<div style="text-align:center;margin-top:10px;"><a href="#" onclick="return eurotext_closeme()" class="et_btt"><?php echo $this->__("Save"); ?></a></div>
<div>&nbsp;</div>

<script>
var eurotext_selectproducts_url="<?php echo $this->getSelectProductsUrl(); ?>";
var eurotext_selectproducts_saveurl="<?php echo $this->getSelectProductsSaveUrl(); ?>";
var eurotext_pagesize="<?php echo $page_size; ?>";
var eurotext_page="<?php echo $current_page; ?>";
var eurotext_catids="<?php echo implode(",",$this->getOpenCatIds()); ?>";
var eurotext_formkey="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>";
var eurotext_projectid="<?php echo $this->getRequest()->getParam("id"); ?>";
jQuery(document).ready(function()
{
	eurotext_selectedproducts_send(new Array(),null);

	jQuery("#filter_status").change(function()
	{
		eurotext_findproducts();

		return false;
	});

	jQuery("#filter_stock").change(function()
	{
		eurotext_findproducts();

		return false;
	});

	jQuery("#filter_product_type").change(function()
	{
		eurotext_findproducts();

		return false;
	});


    jQuery(".eurotext_catsel").click(function()
    {
       var catid=jQuery(this).attr("x-catid");
       var catstate=jQuery(this).attr("x-state");

        postdata=new Array();
        postdata['catid']=catid;

        if (catstate=="checked")
        {
            postdata['select']='unsetcat';
        }
        else
        {
            postdata['select']='setcat';
        }

       eurotext_selectedproducts_send(postdata,null);
    });

	jQuery(".eurotext_selectproducts_allvisible").click(function()
	{
		var postdata=new Array();

		<?php
			echo "postdata['cnt']=".count($visibleProductIds).";";
			for($i=0; $i<count($visibleProductIds); $i++)
			{
				echo "postdata['product_id_".$i."']=".$visibleProductIds[$i].";";
				echo "postdata['set_".$i."']='enabled';";
			}
		?>

		jQuery(".et_selproductitem").attr("checked","checked");

		eurotext_selectedproducts_send(postdata,null);
	});

	jQuery(".eurotext_selectproducts_all").click(function()
	{
		var postdata=new Array();

		var postdata=new Array();
		postdata['cnt']=0;
		postdata['select']='all';

		jQuery(".et_selproductitem").attr("checked","checked");

		eurotext_selectedproducts_send(postdata,null);
	});

	jQuery(".eurotext_selectproducts_none").click(function()
	{
		var postdata=new Array();
		postdata['cnt']=0;
		postdata['select']='none';

		jQuery(".et_selproductitem").attr("checked",false);

		eurotext_selectedproducts_send(postdata,null);
	});

	jQuery('#find_products').keypress(function (e)
	{
		if (e.which == 13)
		{
			e.preventDefault();
			eurotext_findproducts();
		}
	});

	jQuery('.eurotext_page').keypress(function (e)
	{
		eurotext_page=jQuery(this).val();
		if (e.which == 13)
		{
			e.preventDefault();
			eurotext_findproducts();
		}
	});

	jQuery('.eurotext_pagesize').change(function (e)
	{
		eurotext_pagesize=jQuery(this).val();
		eurotext_findproducts();
	});
});
</script>