<?php
// allow utf8-detection: öäü€

// Read Settings:
$helper=Mage::helper('eurotext_translationmanager');;
$et_username=$helper->getSetting("eurotext_username");
$et_password=Mage::helper('core')->decrypt($helper->getSetting("eurotext_password"));
$et_customerid=$helper->getSetting("eurotext_customerid");

$et_products_per_file=$helper->getSetting("et_products_per_file","20");
$et_categories_per_file=$helper->getSetting("et_categories_per_file","20");
$et_cmspages_per_file=$helper->getSetting("et_cmspages_per_file","20");

// Test ftp login:
$statusMessage="";
if (trim($et_username)!="")
{
	$rv=$helper->testFtpConnection();
	$statusMessage=$rv['statusmessage'];
}

if ($helper->getDebugMode())
{
    echo '<div style="background-color:red;padding:3px;color:white;">Debug-Mode is active!</div>';
}


echo "<script type='text/javascript'>";
echo "var eurotext_saveurl='".$this->getSaveUrl()."';";
echo "var eurotext_formkey='".Mage::getSingleton('core/session')->getFormKey()."';";
echo "</script>";

?>

<div class="eurotext_confighead"><?php echo $this->__("Settings"); ?></div>
<div class="eurotext_config">
	<div style="padding:10px;">
		<table cellpadding="0" cellspacing="0">
			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("User name"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="text" id="et_username" value="<?php echo $et_username; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext"></td>
			</tr>
			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("Password"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="password" id="et_password" value="<?php echo $et_password; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext"></td>
			</tr>
			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("Customer ID"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="text" id="et_customerid" value="<?php echo $et_customerid; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext"></td>
			</tr>
			<tr>
				<td class="eurotext_edittext" colspan="4">&nbsp;</td>
			</tr>
			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("Products per file"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="number" id="et_products_per_file" value="<?php echo $et_products_per_file; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext">(<?php echo $this->__("Minimum"); ?>: <?php echo $helper->getExportProductsMinPerFile(); ?>)</td>
			</tr>
			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("Categories per file"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="number" id="et_categories_per_file" value="<?php echo $et_categories_per_file; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext">(<?php echo $this->__("Minimum"); ?>: <?php echo $helper->getExportCategoriesMinPerFile(); ?>)</td>
			</tr>
<!--			<tr>
				<td class="eurotext_edittext"><?php echo $this->__("CMS pages per file"); ?>:</td>
				<td class="eurotext_edittext">&nbsp;</td>
				<td class="eurotext_edittext"><input type="number" id="et_cmspages_per_file" value="<?php echo $et_cmspages_per_file; ?>" autocomplete="off" /></td>
				<td class="eurotext_edittext"><img title="" src="" /></td>
			</tr>-->
			<tr>
				<td class="eurotext_edittext" colspan="4">&nbsp;</td>
			</tr>
			<tr>
				<td class="eurotext_edittext" colspan="4" style="text-align:center;"><a id="eurotext_savebtt" href="#" onclick="return eurotext_savesettings()" class="et_btt"><?php echo $this->__("Save"); ?></a></td>
			</tr>
		</table>
		
		<div>&nbsp;</div>
		<div><?php echo $statusMessage; ?></div>
		
		<?php if ($helper->urlKeyScopeIsGlobal())
		{
			?>
			<div style="margin-top:20px;">
				<?php echo $this->__('Currently your Magento installation is not capable to save translated url keys for products and categories.'); ?><br>
				<a href="<?php echo $this->getUpgradeScopeUrl(); ?>"><?php echo $this->__('Click here to change the scope of url keys to enable translation of url keys for products and categories. (Attention: This can not be undone!)'); ?></a>
			</div>
			<?php
		}
		else
		{
			?>
			<div style="margin-top:20px;">
				<?php echo $this->__("Your Magento installation allows the translation of URLs of categories and products."); ?></a>
			</div>
			<?php
		}
		?>
	</div>	
</div>

<div>&nbsp;</div>

<div class="eurotext_confighead"><?php echo $this->__("Language settings"); ?></div>
<div class="eurotext_config">
	<div style="padding:10px;">
		<table cellpadding="0" cellspacing="0">
			<tr>
				<td class='et_th' colspan="2"><?php echo $this->__("Your Magento languages"); ?>:</td>		
				<td class='et_th'>&nbsp;</td>
				<td class='et_th'>&nbsp;</td>
				<td class='et_th'>&nbsp;</td>
				<td class='et_th' colspan="2"><?php echo $this->__("Language of the translation portal"); ?>:</td>
			</tr>
			<?php
				$stores=$this->getStoreviews();
				foreach($stores as $store)
				{
					$localeInfo=$helper->getLocaleInfoByMagentoLocale($store['locale']);
				
					echo "<tr>";
					echo "<td class='et_tc'>".$store['name']."</td>";
					echo "<td class='et_tc'>".$store['locale']."</td>";
					echo "<td class='et_tc'>&nbsp;</td>";
					echo "<td class='et_tc'>&lt;----&gt;</td>";
					echo "<td class='et_tc'>&nbsp;</td>";			
					echo "<td class='et_tc'>".$localeInfo['lang_name']."</td>";
					echo "<td class='et_tc'>".$localeInfo['locale_eurotext']."</td>";
					echo "</tr>";
				}
			?>
		</table>		
	</div>
</div>

<div>&nbsp;</div>

<div class="eurotext_confighead"><?php echo $this->__("System requirements"); ?>:</div>
<div class="eurotext_config">
	<div style="padding:10px;">
<?php

$items=array();

{
	$item=array();
	$item['name']="PHP-Version";
	$item['ok']=(version_compare(PHP_VERSION, '5.2.0') >= 0);	// min 5.2.0
	$item['value_now']=PHP_VERSION;
	$item['value_required']="min 5.2.0";
	array_push($items,$item);
}

{
	$item=array();
	$item['name']="FTP-Extension";
	$item['ok']=function_exists("ftp_connect");
	$item['value_now']=function_exists("ftp_connect") ? $this->__("Installed") : $this->__("Missing");
	$item['value_required']=$this->__("Installed");
	array_push($items,$item);
}

{
	$item=array();
	$item['name']="ZIP-Extension";
	$item['ok']=class_exists("ZIPArchive");
	$item['value_now']=class_exists("ZIPArchive") ? $this->__("Installed") : $this->__("Missing");
	$item['value_required']=$this->__("Installed");
	array_push($items,$item);
}

echo "<table cellpadding=0 cellspacing=0>";
{	
	echo "<tr>";
	echo " <td class='et_th'>".$this->__("Designation")."</td>";
	echo " <td class='et_th'>".$this->__("Current value")."</td>";
	echo " <td class='et_th'>".$this->__("Required value")."</td>";
	echo "</tr>";
}
foreach($items as $item)
{	
	echo "<tr>";
	echo " <td class='et_tc'>".$item['name']."</td>";
	echo " <td class='et_tc'>".$item['value_now']."</td>";
	echo " <td class='et_tc'>".$item['value_required']."</td>";
	echo "</tr>";
}
echo "</table>";

echo "<div style='margin-top:20px;'>".$this->__("Current value for 'max_execution_time'").": ".ini_get("max_execution_time")."s</div>";

?>
</div>
</div>